### ISSUE TITLE
Move URL's logic to a service or helper under `lib`

### ISSUE THREAD

**Issue by mbaraa** [GDSC-ASU/url-shortener#3]
The api `src/routes/+page.server.js` shouldn't do the logic inside of it, but rather it should just receive the request's data and send them to a service.

Also rename the file to `+server.js`, more info why [here](https://www.reddit.com/r/sveltejs/comments/x7jdy7/the_differences_between_pagejs_pageserverjs_and/), so you'd keep the `load` function in `+page.server.js`, but the rest api handlers should be moved to `src/routes/api/url/+server.js`.

**Comment by Dimah02** [comment]
Hello Baraa,
I want to let you know that all issues have been resolved. I accidentally merged the PR, but everything is functioning perfectly. 😅

**Comment by mbaraa** [comment]
Just a couple of things:
* check my comment in #2
* db calls should be moved under `lib/db` or `db/services` in [this](https://github.com/GDSC-ASU/url-shortener/blob/746b410cabefecb7c68e0f97bea905bba72bcb22/src/routes/api/url/%2Bserver.js) file, since APIs should never do any logic, but rather receive data from the client pass them to a service then respond with an appropriate response
* after creating the service refactor [this](https://github.com/GDSC-ASU/url-shortener/blob/main/src/routes/api/url/%2Bserver.js) file to retrieve the data directly from the service instead of using the API
